//action常量

//访客聊窗
export const GET_WEBVIEW = 'GET_WEBVIEW';
export const SET_WEBVIEW = 'SET_WEBVIEW';
export const CLEAR_WEBVIEW_PROGRESS = 'CLEAR_WEBVIEW_PROGRESS';

//质检
export const GET_QUALITYTEST = 'GET_QUALITYTEST';
export const NEW_QUALITYTEST = 'NEW_QUALITYTEST';
export const EDITOR_QUALITYTEST = 'EDITOR_QUALITYTEST';
export const REMOVE_QUALITYTEST = 'REMOVE_QUALITYTEST';

export const STOPTIME_QERUEST = 'STOPTIME_QERUEST';
export const STARTTIME_QERUEST = 'STARTTIME_QERUEST';
export const STOPTIME_SUCCESS = 'STOPTIME_SUCCESS';
export const STARTTIME_SUCCESS = 'STARTTIME_SUCCESS';

//message
export const SEND_MESSAGE = 'SEND_MESSAGE';
export const ADD_MESSAGE = 'ADD_MESSAGE';
export const HISTORY_MESSAGE_QERUEST = 'HISTORY_MESSAGE_QERUEST';
export const ADD_BADGE_COUNT = 'ADD_BADGE_COUNT';
export const CLEAR_BADGE_COUNT = 'CLEAR_BADGE_COUNT';
export const SEND_EMOJI = 'SEND_EMOJI';
export const SET_SLIDE_STATE = 'SET_SLIDE_STATE';
export const SEND_COLOR = 'SEND_COLOR';
export const GET_EMOJI_BLOCK = 'GET_EMOJI_BLOCK';
export const CLOSE_BLOCK = 'CLOSE_BLOCK';
export const SEND_IMG_ATATE = 'SEND_IMG_ATATE';
export const EDITOR_EMPTY = 'EDITOR_EMPTY';
export const MYSEND_COLOR = 'MYSEND_COLOR';

export const RECEIVE_MESSAGE = 'RECEIVE_MESSAGE';

export const ADD_CHANNEL = 'ADD_CHANNEL';
export const CHANGE_CHANNEL = 'CHANGE_CHANNEL';
export const RECEIVE_CHANNEL = 'RECEIVE_CHANNEL';

export const SIGNUP_USER = 'SIGNUP_USER';
export const SIGNIN = 'SIGNIN';

export const AUTH_LOAD = 'AUTH_LOAD';
export const AUTH_LOAD_SUCCESS = 'AUTH_LOAD_SUCCESS';

export const AUTH_SIGNIN = 'AUTH_SIGNIN';
export const AUTH_SIGNIN_SUCCESS = 'AUTH_SIGNIN_SUCCESS';

export const AUTH_SIGNOUT = 'AUTH_SIGNOUT';
export const AUTH_SIGNOUT_SUCCESS = 'AUTH_SIGNOUT_SUCCESS';

export const AUTH_SIGNUP_SUCCESS = 'AUTH_SIGNUP_SUCCESS';
export const AUTH_SIGNUP = 'AUTH_SIGNUP';

export const RECEIVE_SOCKET = 'RECEIVE_SOCKET';
//goods.js
export const LOADING = 'LOADING';
export const LOAD_NEXT_PAGE = 'LOAD_NEXT_PAGE';
export const REFRESH_LIST = 'REFRESH_LIST';
export const REFRESH = 'REFRESH';
export const CLEAR_DATA = 'CLEAR_DATA';

//news.js
export const LOAD_NEXT_NEW = 'LOAD_NEXT_NEW';
export const CLOSE_NEW = 'CLOSE_NEW';
export const CURRENT_NEW = 'CURRENT_NEW';

//language
export const CHANGE_LANGUAGE = 'CHANGE_LANGUAGE';

//theme
export const GET_THEME = 'GET_THEME';
export const GET_THEME_PROGRESS = 'GET_THEME_PROGRESS';
export const THEME_SETTING = 'THEME_SETTING';

//排队列表
export const QUEUE_LIST = 'QUEUE_LIST';
export const QUEUE_LIST_COLUMNS = 'QUEUE_LIST_COLUMNS';
export const GET_ALL_QUEUE_COLUMNS = 'GET_ALL_QUEUE_COLUMNS';

//常用话术
export const GET_PERSON_COMMON_WORLD = 'GET_PERSON_COMMON_WORLD';
export const GET_ALL_COMMON_WORLD = 'GET_ALL_COMMON_WORLD';

//轨迹
export const TRAJECTORY = 'TRAJECTORY';
export const GET_TRAJECTORY = 'GET_TRAJECTORY';
export const TRACONTENT = 'TRACONTENT';
export const GET_TRACONTENT = 'GET_TRACONTENT';
export const TRAORDERS = 'TRAORDERS';
export const GET_TRAORDERS = 'GET_TRAORDERS';
export const TRASHOPS = 'TRASHOPS';
export const GET_TRASHOPS = 'GET_TRASHOPS';
export const TRAALL = 'TRAALL';
export const GET_TRAALL = 'GET_TRAALL';
export const GET_TRAWEB = 'GET_TRAWEB';
export const REFRESH_TRAIL = "REFRESH_TRAIL";
export const SET_NTID = "SET_NTID";

//图表
export const SET_CHARTFILTER = 'SET_CHARTFILTER';
export const GET_CHARTDATA = 'GET_CHARTDATA';
export const GET_CHARTTYPE = 'GET_CHARTTYPE';
export const GET_CHARTERROR = 'GET_CHARTERROR';

//企业设置
export const GET_VISITORDATA='GET_VISITORDATA';
export const DISTRIBUTION='DISTRIBUTION';
export const DATA_REQUEST='DATA_REQUEST';
export const DATATYPE_REQUEST='DATATYPE_REQUEST';
export const GET_ROBOT_OFF='GET_ROBOT_OFF';
export const GET_ROLE_LIST='GET_ROLE_LIST';
export const GET_USER_TYPE='GET_USER_TYPE';
export const GET_ROBOT_URL='GET_ROBOT_URL';
export const GET_USER_SKILL_TAG='GET_USER_SKILL_TAG';
export const SEND_ROBOT_OFF='SEND_ROBOT_OFF';
export const EDITOR_ROBOT_OFF='EDITOR_ROBOT_OFF';
export const GET_ROLE_LIMIT_DATA='GET_ROLE_LIMIT_DATA';
export const GET_INFO_REQUEST='GET_INFO_REQUEST';
export const SEND_INFO_REQUEST='SEND_INFO_REQUEST';
export const GET_ACCOUNT_TABLEDATE='GET_ACCOUNT_TABLEDATE';
export const GET_FAST_ACCOUNT='GET_FAST_ACCOUNT';
export const GET_ACCOUNT_LIST='GET_ACCOUNT_LIST';
export const GET_EDITOR_ROLE='GET_EDITOR_ROLE';
export const SET_NEW_ROLE='SET_NEW_ROLE';
export const SET_EDITOR_ROLE='SET_EDITOR_ROLE';
export const SET_EDITOR_ROLE_STATUS='SET_EDITOR_ROLE_STATUS';
export const DELETE_ROLE='DELETE_ROLE';
export const ROLE_MANAGER='ROLE_MANAGER';
export const GET_QUEUE_MANAGE='GET_QUEUE_MANAGE';
export const SET_QUEUE_MANAGE='SET_QUEUE_MANAGE';
export const CLEAR_QUEUE_PROGRESS='CLEAR_QUEUE_PROGRESS';
export const ADD_GROUP='ADD_GROUP';
export const EDITOR_GROUP='EDITOR_GROUP';
export const EDITOR_GROUP_RANK='EDITOR_GROUP_RANK';
export const REMOVE_GROUP='REMOVE_GROUP';
export const REMOVE_ACCOUNT_LIST='REMOVE_ACCOUNT_LIST';
export const REMOVE_ACCOUNTS='REMOVE_ACCOUNTS';
export const SEND_NEW_ACCOUNT='SEND_NEW_ACCOUNT';
export const SEND_MIGRATE_ACCOUNTS='SEND_MIGRATE_ACCOUNTS';
export const GET_ACCOUNT_SEARCH_DATA='GET_ACCOUNT_SEARCH_DATA';
export const EDITOR_ACCOUNT_LIST='EDITOR_ACCOUNT_LIST';
export const EDITOR_PASSWORD='EDITOR_PASSWORD';
export const EDITOR_PASSWORD_MSG_CLEAR='EDITOR_PASSWORD_MSG_CLEAR';
export const GET_EDIT_DATA='GET_EDIT_DATA';
export const GET_NEW_VISITOR_TYPE='GET_NEW_VISITOR_TYPE';
export const GET_EDITOR_VISITOR_TYPE='GET_EDITOR_VISITOR_TYPE';
export const REMOVE_VISITOR_TYPE='REMOVE_VISITOR_TYPE';
export const GET_VISITOR='GET_VISITOR';
export const GET_NEW_VISITOR='GET_NEW_VISITOR';
export const GET_EDITOR_VISITOR='GET_EDITOR_VISITOR';
export const REMOVE_VISITOR='REMOVE_VISITOR';
export const CLEAR_VISITOR_PROGRESS='CLEAR_VISITOR_PROGRESS';
export const CLEAR_VISITOR_ITEM_PROGRESS='CLEAR_VISITOR_ITEM_PROGRESS';
export const SET_AUTO_RESPONSE='SET_AUTO_RESPONSE';
export const RESET_ANWER_PROGRESS='RESET_ANWER_PROGRESS';
export const SET_AUTO_RESPONSE_GREET='SET_AUTO_RESPONSE_GREET';

export const GET_ALL_TIPS_DATA='GET_ALL_TIPS_DATA';
export const GET_SEARCH_TIPS='GET_SEARCH_TIPS';
export const GET_TIPS_GROUP_DATA='GET_TIPS_GROUP_DATA';
export const NEW_TIPS_GROUP='NEW_TIPS_GROUP';
export const EDIT_TIPS_GROUP='EDIT_TIPS_GROUP';
export const EDIT_TIPS_GROUP_RANK='EDIT_TIPS_GROUP_RANK';
export const REMOVE_TIPS_GROUP='REMOVE_TIPS_GROUP';
export const GET_TIPS='GET_TIPS';
export const GET_NEW_TIPS='GET_NEW_TIPS';
export const GET_EDITOR_TIPS='GET_EDITOR_TIPS';
export const GET_EDITOR_TIPS_RANK='GET_EDITOR_TIPS_RANK';
export const REMOVE_TIPS='REMOVE_TIPS';
export const IMPORT_COMMON_WORD='IMPORT_COMMON_WORD';

export const GET_REGION='GET_REGION';
export const GET_PROVINCE='GET_PROVINCE';
export const GET_CITY='GET_CITY';

export const GET_USERGROUPLIST='GET_USERGROUPLIST';

//自动应答问候语
export const GET_AUTO_WELCOME = 'GET_AUTO_WELCOME';
export const GET_TEMPLATE_AUTO_WELCOME = 'GET_TEMPLATE_AUTO_WELCOME';
export const GET_AUTO_RESPONSE = 'GET_AUTO_RESPONSE';
export const GET_TEMPLATE_AUTO_RESPONSE = 'GET_TEMPLATE_AUTO_RESPONSE';

//个人设置
export const GET_INFOMATION = 'GET_INFOMATION';
export const SET_INFOMATION = 'SET_INFOMATION';
export const GET_INFOMATION_PROGRESS = 'GET_INFOMATION_PROGRESS';
export const GET_CHATSET_PROGRESS = 'GET_CHATSET_PROGRESS';
export const GET_CHATSET = 'GET_CHATSET';
export const SET_CHATSET = 'SET_CHATSET';
export const GET_REPLY_CODE = 'GET_REPLY_CODE';
export const SET_REPLY_CODE = 'SET_REPLY_CODE';
export const GET_REPLY_CODE_PROGRESS = 'GET_REPLY_CODE_PROGRESS';
export const GET_INTELLIGENT = 'GET_INTELLIGENT';
export const SET_INTELLIGENT = 'SET_INTELLIGENT';
export const GET_INTELLIGENT_PROGRESS = 'GET_INTELLIGENT_PROGRESS';

//智能分配
export const GET_REALTIME_INTELLDIS_DATA = 'GET_REALTIME_INTELLDIS_DATA';
export const MAKE_USERS = 'MAKE_USERS';
export const GET_CURSTEM = 'GET_CURSTEM';
export const GET_SKILLTAG_CURSTEM = 'GET_SKILLTAG_CURSTEM';
export const EDITOR_USER = 'EDITOR_USER';
export const DEL_USER = 'DEL_USER';
export const GET_USER = 'GET_USER';
export const USER_CHECKED = 'USER_CHECKED';

export const GET_USERTERMINAL = 'GET_USERTERMINAL';
export const GET_ALL_REGION = 'GET_ALL_REGION';

//敏感词
export const GET_SENSITIVEWORD = "GET_SENSITIVEWORD";
export const SET_SENSITIVEWORD = "SET_SENSITIVEWORD";

//技能标签
export const GET_SKILLTAG = "GET_SKILLTAG";
export const NEW_SKILLTAG = "NEW_SKILLTAG";
export const DEL_SKILLTAG = "DEL_SKILLTAG";
export const GET_LISTINFO = "GET_LISTINFO";
export const EDITOR_SKILLTAG = "EDITOR_SKILLTAG";

//常见问题
export const Faqlist = "Faqlist";
export const Get_Faqlist = "Get_Faqlist";

export const ADD_COMPANY_FAQGROUP = "ADD_COMPANY_FAQGROUP";
export const ADD_TEMPLATE_FAQGROUP = "ADD_TEMPLATE_FAQGROUP";
export const EDIT_COMPANY_FAQGROUP = "EDIT_COMPANY_FAQGROUP";
export const EDIT_COMPANY_FAQGROUP_RANK = "EDIT_COMPANY_FAQGROUP_RANK";
export const DEL_COMPANY_FAQGROUP = "DEL_COMPANY_FAQGROUP";
export const GET_COMPANY_FAQGROUP_LIST = "GET_COMPANY_FAQGROUP_LIST";

export const ADD_COMPANY_FAQITEM = "ADD_COMPANY_FAQITEM";
export const EDIT_COMPANY_FAQITEM = "EDIT_COMPANY_FAQITEM";
export const EDIT_COMPANY_FAQITEM_RANK = "EDIT_COMPANY_FAQITEM_RANK";
export const DEL_COMPANY_FAQITEM = "DEL_COMPANY_FAQITEM";
export const GET_COMPANY_FAQITEM_LIST = "GET_COMPANY_FAQITEM_LIST";
export const GET_TEMPLATES_GROUP_LIST = "GET_TEMPLATES_GROUP_LIST";
export const GET_COMPANY_SEARCH_COMPANY_DATA = "GET_COMPANY_SEARCH_COMPANY_DATA";
export const GET_ALL_COMPANY_FAQ_ITEM_DATA = "GET_ALL_COMPANY_FAQ_ITEM_DATA";
export const IMPORT_FAQ_QUESTION = "IMPORT_FAQ_QUESTION";
export const CLEAR_FAQ_ITEM_DATA = "CLEAR_FAQ_ITEM_DATA";

//平台账号管理
export const ACCOUNT = 'ACCOUNT';
export const GET_ACCOUNT = 'GET_ACCOUNT';
export const ACCOUNT_PROGRESS = 'ACCOUNT_PROGRESS';

//关键页面 essential
export const ESSENTIAL = 'ESSENTIAL';
export const GET_ESSENTIAL = 'GET_ESSENTIAL';
export const DEL_ESSENTIAL = 'DEL_ESSENTIAL';
export const NEW_ESSENTIAL = 'NEW_ESSENTIAL';

//UI层向逻辑层发送事件
export const SENDMESSAGE = 'UI_SENDMESSAGE';  //发送消息
export const TABSELECTED = 'UI_TABSELECTED';  //选中会话标签
export const TABCLOSED = 'UI_TABCLOSED';  //选中会话标签
export const UI_REQUEST_COOPERATE = 'UI_REQUEST_COOPERATE';  //协同会话
export const UI_REQUEST_COOPERATE_ACTION = 'UI_REQUEST_COOPERATE_ACTION';  //协同会话
export const UI_REQUEST_SUBMIT_SUMMARY = 'UI_REQUEST_SUBMIT_SUMMARY';  //咨询总结
export const UI_REQUEST_EVALUATION = 'UI_REQUEST_EVALUATION';  //咨询邀请

export const GET_TOOLBAR_REQUEST = 'GET_TOOLBAR_REQUEST';

//待处理
export const GET_PEND_TREATMENT = 'GET_PEND_TREATMENT';
export const PEND_TREATMENT = 'PEND_TREATMENT';

//KPI获取报表列表
export const GET_KPI = 'GET_KPI';
export const KPI_LIST = 'KPI_LIST';
export const REPOET_VALUE = 'REPOET_VALUE';

//KPI报表订阅，删除订阅功能
export const  UNSUBSCRIBE_PROGRESS = 'UNSUBSCRIBE_PROGRESS';
export const  SUBSCRIBE_PROGRESS = 'SUBSCRIBE_PROGRESS';
export const RESET_SUBSCRIBE_PROGRESS = ' RESET_SUBSCRIBE_PROGRESS'

//获取kpi头部四个列表
export const GET_CLIENTTAB = 'GET_CLIENTTAB';
export const GET_PEND_CLIENTTAB = 'GET_PEND_CLIENTTAB';

//获取kpi权限
export const GET_COMPETENCE_TAB = 'GET_COMPETENCE_TAB';


//获取我关注报表列表
export const ATTENTION_LIST = 'ATTENTION_LIST';
export const GET_ATTENTION = 'GET_ATTENTION';
export const UNSUBSCRIBE = 'UNSUBSCRIBE';
export const SUBSCRIBE = 'SUBSCRIBE';

//获取报表筛选条件
export const FILTER_REPORT = 'FILTER_REPORT';
export const FILTER_CONDITIONS = 'FILTER_CONDITIONS';
export const FILTER_DATA = 'FILTER_DATA';
export const GROPU_USER = 'GROPU_USER';
export const NEW_FILTER_REPORT = 'NEW_FILTER_REPORT';

//获取周报/月报数据
export const GET_WEEKLY = 'GET_WEEKLY';
export const REPOET_WEEKLY = 'REPOET_WEEKLY';

////获取客服往来明细数据
//export const CUSTOMER_SERVICE = 'CUSTOMER_SERVICE';
//export const SELECTION_COLUMN = 'SELECTION_COLUMN';

//KPI报表获取全部选择显示内容
export const GET_ALL_COLUMNS = 'GET_ALL_COLUMNS';

//当前报表显示列
export const GET_SELECT_COLUMNS = 'GET_SELECT_COLUMNS';
export const SET_SELECT_COLUMNS = 'SET_SELECT_COLUMNS';

//咨询总结
export const GET_SUMMARY_ALL = 'GET_SUMMARY_ALL';
export const GET_SUMMARY_ALL_ITEMS = 'GET_SUMMARY_ALL_ITEMS';
export const ADD_SUMMARY_TYPE = 'ADD_SUMMARY_TYPE';
export const EDIT_SUMMARY_TYPE = 'EDIT_SUMMARY_TYPE';
export const REMOVE_SUMMARY_TYPE = 'REMOVE_SUMMARY_TYPE';
export const IS_SET_COMMON_OK = 'IS_SET_COMMON_OK';
export const CLEAR_SET_COMMON_MSG = 'CLEAR_SET_COMMON_MSG';
export const ADD_SUMMARY_LEAF = 'ADD_SUMMARY_LEAF';
export const GET_SUMMARY_LEAF = 'GET_SUMMARY_LEAF';
export const IMPORT_SUMMARY = 'IMPORT_SUMMARY';
export const EDIT_SUMMARY_LEAF = 'EDIT_SUMMARY_LEAF';
export const EDIT_SUMMARY_LEAF_RANK = 'EDIT_SUMMARY_LEAF_RANK';
export const REMOVE_SUMMARY_LEAF = 'REMOVE_SUMMARY_LEAF';
export const GET_SUMMARY_LEAF_SEARCH = 'GET_SUMMARY_LEAF_SEARCH';
export const GET_CHATSUMMARY_ALL = 'GET_CHATSUMMARY_ALL';
export const EDIT_SUMMARY_TYPE_RANK = 'EDIT_SUMMARY_TYPE_RANK';
export const GET_COMMONSUMMARY = 'GET_COMMONSUMMARY';

//个人常用话术
export const GET_PERSON_TIPS_TYPE = 'GET_PERSON_TIPS_TYPE';
export const NEW_PERSON_TIPS_TYPE = 'NEW_PERSON_TIPS_TYPE';
export const EDIT_PERSON_TIPS_TYPE = 'EDIT_PERSON_TIPS_TYPE';
export const EDIT_PERSON_TIPS_TYPE_RANK = 'EDIT_PERSON_TIPS_TYPE_RANK';
export const DEL_PERSON_TIPS_TYPE = 'DEL_PERSON_TIPS_TYPE';

export const GET_PERSON_TIPS_ITEM = 'GET_PERSON_TIPS_ITEM';
export const NEW_PERSON_TIPS_ITEM = 'NEW_PERSON_TIPS_ITEM';
export const EDIT_PERSON_TIPS_ITEM = 'EDIT_PERSON_TIPS_ITEM';
export const EDIT_PERSON_TIPS_ITEM_RANK = 'EDIT_PERSON_TIPS_ITEM_RANK';
export const DEL_PERSON_TIPS_ITEM = 'DEL_PERSON_TIPS_ITEM';
export const IMPORT_PERSON_TIPS = 'IMPORT_PERSON_TIPS';
export const CLEAR_PERSONTIPS_PROGRESS = 'CLEAR_PERSONTIPS_PROGRESS';

//配置项级别
export const GET_INDIVIDUAL_LEVEL = 'GET_INDIVIDUAL_LEVEL';
export const GET_ALL_CONFIG_LEVEL = 'GET_ALL_CONFIG_LEVEL';
export const EDIT_CONFIG_LEVEL = 'EDIT_CONFIG_LEVEL';

//咨询评价
export const GET_EVALUATION = 'GET_EVALUATION';
export const EDIT_EVALUATION = 'EDIT_EVALUATION';
export const CLEAR_EVALUATION_PROGRESS = 'CLEAR_EVALUATION_PROGRESS';

//留言设置
export const GET_LEAVE_MESSAGE = 'GET_LEAVE_MESSAGE';
export const EDIT_LEAVE_MESSAGE = 'EDIT_LEAVE_MESSAGE';

//黑名单
export const GET_SEARCH_BLACKLIST = 'GET_SEARCH_BLACKLIST';
export const GET_ALL_BLACKLIST = 'GET_ALL_BLACKLIST';
export const ADD_BLACKLIST = 'ADD_BLACKLIST';
export const REMOVE_BLACKLIST = 'REMOVE_BLACKLIST';
export const CLEAR_PROGRESS = 'CLEAR_PROGRESS';
